### ISSUE TITLE
Nejde rozjet na php7.2

### ISSUE THREAD

**Issue by h4kuna** [webnazakazku/Library-IS#4]
Ahoj,
nevím do jaké míry toto řešit ale já na 5.6 už nevyvíjím. A pokud by se to mělo dál rozvíjet musí se pokrýt obě verze, což si myslím že není problém. Jen v composeru jsou podle mě balíčky, které se nepoužívají a pak které tento upgrade komplikují.

**Comment by petrparolek** [comment]
na 7.1 to jede ok, zřejmě jsou tam starší balíčky

**Comment by h4kuna** [comment]
Když jsem dal `composer install`. Nainstaloval se kdyby/doctrine:3.2.1 ale je potřeba 3.3.0 takže pokud to půjde opravit bez ztráty kytičky tak to pojede.

**Comment by petrparolek** [comment]
pošli PR

**Comment by h4kuna** [comment]
#6 PR

**Comment by petrparolek** [comment]
díky

**Comment by petrparolek** [comment]
už vše jede i pod PHP 7.2
